### ISSUE TITLE
Error for creating environment with YAML

### ISSUE THREAD

**Issue by whoisleehom** [ratschlab/st-rep#1]
I tried to use the provided YAML file to create the environment by:

**mamba env create -f=environments/conda_st_rep_python_snakemake.yaml**

But the command failed, and the error message was:

**Pip subprocess error:
ERROR: Ignored the following versions that require a different python version: 0.13.0 Requires-Python >=3.10; 0.3.0rc0 Requires-Python >=3.10; 0.52.0 Requires-Python >=3.6,<3.9; 0.52.0rc3 Requires-Python >=3.6,<3.9; 1.6.0 Requires-Python >=3.10; 1.7.0 Requires-Python >=3.10; 1.8.0 Requires-Python >=3.11; 1.9.0 Requires-Python >=3.11; 1.9.1 Requires-Python >=3.11; 1.9.2 Requires-Python >=3.11; 3.3 Requires-Python >=3.10; 3.3rc0 Requires-Python >=3.10; 3.5.0 Requires-Python >=3.10; 3.5.0.dev1 Requires-Python >=3.10; 3.5.0.dev3 Requires-Python >=3.10; 3.5.0.dev4 Requires-Python >=3.10; 3.5.0.dev5 Requires-Python >=3.10; 3.5.0.dev6 Requires-Python >=3.10; 3.5.0.dev7 Requires-Python >=3.10; 3.5.0.dev8 Requires-Python >=3.10; 3.5.0rc1 Requires-Python >=3.10; 3.5.0rc2 Requires-Python >=3.10; 3.6.0.dev1 Requires-Python >=3.10; 8.19.0 Requires-Python >=3.10; 8.20.0 Requires-Python >=3.10; 8.21.0 Requires-Python >=3.10; 8.22.0 Requires-Python >=3.10; 8.22.1 Requires-Python >=3.10; 8.22.2 Requires-Python >=3.10; 8.23.0 Requires-Python >=3.10; 8.24.0 Requires-Python >=3.10; 8.25.0 Requires-Python >=3.10; 8.26.0 Requires-Python >=3.10
ERROR: Could not find a version that satisfies the requirement python-graphviz==0.20.1 (from versions: none)
ERROR: No matching distribution found for python-graphviz==0.20.1

failed

CondaEnvException: Pip failed**

**Comment by KalinNonchev** [comment]
Hi @whoisleehom, 

thank you for your question. This distribution is available under the pypi website [here](https://pypi.org/project/graphviz/0.20.1) and it should be accessible. Please ensure you are using the latest pip version and try installing it manually:

`pip install graphviz==0.20.1`

Please let me know if you have any further questions.
